### ISSUE TITLE
Nature Assistant V6 Deployment

### ISSUE THREAD

**Issue by Thisisnotharry** [Thisisnotharry/status#10]
.

**Comment by Thisisnotharry** [comment]
Nature Assistant V6 will be released later today - updates will follow here.

**Comment by Thisisnotharry** [comment]
**In Progress** - We are currently in the process of releasing Nature Assistant v6.

**Comment by Thisisnotharry** [comment]
**Monitoring** - We have finished deploying Nature Assistant V6 onto the main bot - we're now checking for any last minute issues.

**Comment by Thisisnotharry** [comment]
**Completed** - For a list of changes, check announcements channel.

**Comment by chrissxo** [comment]
HeLLO EVERYONE
